version: '3.5'

services:


  # cassandra-load-keyspace:
  #     container_name: cassandra-load-keyspace
  #     image: cassandra:latest
  #     depends_on:
  #       - cassandra
  #     # volumes:
  #     #   - ./src/main/schema
  #     command: /bin/bash -c "sleep 60 && echo loading cassandra keyspace && cqlsh cassandra -f /src/main/schema.cql && npm run seed-database"
  
  # cassandra-load-data:
  #     container_name: cassandra-load-data
  #     image: cassandra:latest
  #     depends_on:
  #       - cassandra
  #     # volumes:
  #     #   - ./src/main/cassandra_data.js:/seed.js
  #     command: /bin/bash -c "sleep 60 && echo loading cassandra keyspace && npm run seed-database"

  app:
      build: .
      depends_on:
        - cassandra
      ports:
        - "8000:8000"
      links: 
        - cassandra
      networks: 
        - service
      command: npm start

  cassandra:
      image: cassandra:latest
      container_name: cassandra
      ports:
        - "9042:9042"
      environment:
        - "MAX_HEAP_SIZE=256M"
        - "HEAP_NEWSIZE=128M"
      restart: always
      networks: 
        - service
      # volumes:
        # - ./out/cassandra_data:/var/lib/cassandra
      command: 
         - "sh cassandra-init.sh"
        # - "cqlsh select * from stays"
networks:
  service:
    driver: "bridge"